a = float(input("Give me the first number: ").strip())
b = float(input("Give me the second number: ").strip())
print("Thank you!")
print(f"{a} + {b} = {a + b}")
print(f"{a} - {b} = {a - b}")
print(f"{a} / {b} = {a / b}")
print(f"{a} * {b} = {a * b}")